x-env_file: &env_file
  env_file:
    - .env

services:

  web:
    image: mescalantea/magento:$M2_VERSION-$PHP_VERSION
    build:
      dockerfile: Dockerfile
      context: ./.docker/web
      args:
        PHP_VERSION: ${PHP_VERSION}
        M2_VERSION: ${M2_VERSION}
        M2_REPO_KEY: ${M2_COMPOSER_REPO_KEY}
        M2_REPO_SECRET: ${M2_COMPOSER_REPO_SECRET}
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    ports:
      - $M2_HTTP_PORT:80
    volumes:
      - m2_html:/var/www/html
    extra_hosts:
      - "localhost.sequrapi.com:host-gateway"
    <<: *env_file

  db:
    image: mariadb:$MARIADB_TAG
    ports:
      - $MARIADB_PORT:3306
    <<: *env_file
    volumes:
      - m2_db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      timeout: 3s
      retries: 10

  redis:
    image: redis:$REDIS_TAG
    ports:
      - $REDIS_PORT:6379
    volumes:
      - m2_redis:/data

  elasticsearch:
    image: elasticsearch:$ELASTICSEARCH_TAG
    ports:
      - $ELASTICSEARCH_API_PORT:9200
      - $ELASTICSEARCH_INTERNODE_PORT:9300
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:$ELASTICSEARCH_API_PORT"]
      interval: 3s
      timeout: 3s
      retries: 15
    volumes:
      - m2_elasticsearch:/usr/share/elasticsearch/data
  
volumes:
  m2_db:
  m2_redis:
  m2_elasticsearch:
  m2_html: